# Generated by Django 3.0.4 on 2020-03-30 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200330_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FilePathField(path='pics/img'),
        ),
    ]
